#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\InicioController::index


planets:
    path: /planets/{valorplanet}
    controller: App\Controller\PlanetsController::index

planet:
    path: /planet
    controller: App\Controller\PlanetsController::planet

inicio:
    path: /inicio
    controller: App\Controller\InicioController::index
